Admin/EasyLearnerAdmin/Controllers/TutorController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using System.Transactions;
using EasyLearner.Service.Dto;
using EasyLearner.Service.Exception;
using EasyLearner.Service.Interface;
using EasyLearnerAdmin.Data.DbModel;
using EasyLearnerAdmin.Utility;
using EasyLearnerAdmin.Utility.Common;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using EasyLearner.Service;
using Microsoft.AspNetCore.Identity;
using EasyLearnerAdmin.Data.DbContext;
using Microsoft.AspNetCore.Mvc.Rendering;
using System.Text.RegularExpressions;
using System.Globalization;
using EasyLearner.Service.Enums;
using EasyLearnerAdmin.Models;
using EasyLearnerAdmin.Utility.JqueryDataTable;
using Microsoft.Data.SqlClient;
using System.Globalization;
using System.Data;
using Newtonsoft.Json;

namespace EasyLearnerAdmin.Controllers
{
    [Authorize]
    public class TutorController : BaseController<TutorController>
    {
        #region Field
        private readonly ITutorService _tutorService;

        private readonly IUserService _userService;
        private readonly RoleManager<Role> _roleManager;
        private readonly IGradeService _gradeService;
        private readonly ILessonService _lessonService;
        private readonly ITutorRelevantLesson _relevantLessonService;

        private readonly UserManager<ApplicationUser> _userManager;
        private readonly ILogService _staffLog;
        #endregion

        #region Ctor
        public TutorController(ITutorService tutorService, ILogService staffLog, ITutorRelevantLesson relevantLesson, ILessonService lessonService, UserManager<ApplicationUser> userManager, IUserService userService, RoleManager<Role> roleManager, IGradeService gradeService)
        {
            _tutorService = tutorService;
            _userService = userService;
            _roleManager = roleManager;
            _userManager = userManager;
            _gradeService = gradeService;
            _lessonService = lessonService;
            _relevantLessonService = relevantLesson;
            _staffLog = staffLog;
        }
        #endregion

        #region Method
        public IActionResult Index()
        {
            return View();
        }


        public IActionResult Tutorfilter()
        {
            return View();
        }

        [HttpGet]
        public async Task<IActionResult> GetFilterTutorList(JQueryDataTableParamModel param, TutorFiltorDto model)
        {
            using (var txscope = new TransactionScope(TransactionScopeAsyncFlowOption.Enabled))
            {
                try
                {
                    var parameters = CommonMethod.GetJQueryDatatableParamList(param, GetSortingColumnName(param.iSortCol_0));

                    if (model.TutorisActive == true && model.TutorisInActive == false)
                    {
                        parameters.Parameters.Insert(2, new SqlParameter("@IsActive", SqlDbType.Bit) { Value = true });
                    }
                    if (model.TutorisInActive == true && model.TutorisActive == false)
                    {
                        parameters.Parameters.Insert(2, new SqlParameter("@IsActive", SqlDbType.Bit) { Value = false });
                    }

                    parameters.Parameters.Insert(0, new SqlParameter("@Fromdate", SqlDbType.DateTime) { Value = Convert.ToDateTime(model.FromDate).ToString("yyyy/MM/dd") });
                    parameters.Parameters.Insert(1, new SqlParameter("@Todate", SqlDbType.DateTime) { Value = Convert.ToDateTime(model.ToDate).ToString("yyyy/MM/dd") });

                    var allList = await _tutorService.GetFilterTutorReport(parameters.Parameters.ToArray());

                    var total = allList.FirstOrDefault()?.TotalRecords ?? 0;
                    return Json(new
                    {
                        param.sEcho,
                        iTotalRecords = total,
                        iTotalDisplayRecords = total,
                        aaData = allList
                    });
                }
                catch (Exception ex)
                {
                    ErrorLog.AddErrorLog(ex, "GetFilterTutorReport");
                    return Json(new
                    {
                        param.sEcho,
                        iTotalRecords = 0,
                        iTotalDisplayRecords = 0,
                        aaData = ""
                    });
                }
            }
        }

        public IActionResult TutorProfile(long id)
        {
            var result = _tutorService.GetSingle(x => x.Id == id);
            var tutorUserResult = _userService.GetSingle(x => x.Id == result.UserId);
            var tutorDto = new TutorDto()
            {
                TutorName = result.TutorName,
                UserName = tutorUserResult.UserName,
                IsActive = result.IsActive,
                Id = result.Id
            };
            var tempView = Mapper.Map<TutorDto>(tutorDto);
            return View("TutorProfile", tempView);
        }

        [HttpPost]
        public async Task<IActionResult> EditTutorStatus(long id, bool IsActive)
        {
            using (var txscope = new TransactionScope(TransactionScopeAsyncFlowOption.Enabled))
            {
                try
                {
                    var result = _tutorService.GetSingle(x => x.Id == id);
                    result.IsActive = IsActive;
                    var updateResult = await _tutorService.UpdateAsync(result, Accessor, User.GetUserId());
                    if (updateResult != null)
                    {

                        //StaffLog
                        if (User.IsInRole(UserRoles.Staff))
                            await _staffLog.InsertAsync(new Log { CreatedDate = DateTime.UtcNow, StaffId = User.GetUserId(), Description = ResponseConstants.UpdateTutorStatus }, Accessor, User.GetUserId());
                        txscope.Complete();
                        return JsonResponse.GenerateJsonResult(1, ResponseConstants.UpdateTutorStatus);
                    }
                    else
                    {
                        txscope.Dispose();
                        return JsonResponse.GenerateJsonResult(0, ResponseConstants.SomethingWrong);
                    }

                }
                catch (Exception ex)
                {
                    txscope.Dispose();
                    ErrorLog.AddErrorLog(ex, "EditTutorStatus");
                    return JsonResponse.GenerateJsonResult(0, ResponseConstants.SomethingWrong);
                }

            }
        }


        [HttpPost]
        public async Task<IActionResult> EditTutorName(long id, string TutorName)
        {
            using (var txscope = new TransactionScope(TransactionScopeAsyncFlowOption.Enabled))
            {
                try
                {
                    var result = _tutorService.GetSingle(x => x.Id == id);
                    result.TutorName = TutorName;
                    var updateResult = await _tutorService.UpdateAsync(result, Accessor, User.GetUserId());
                    if (updateResult != null)
                    {
                        //StaffLog
                        if (User.IsInRole(UserRoles.Staff))
                            await _staffLog.InsertAsync(new Log { CreatedDate = DateTime.UtcNow, StaffId = User.GetUserId(), Description = ResponseConstants.UpdateTutorName }, Accessor, User.GetUserId());
                        txscope.Complete();
                        return JsonResponse.GenerateJsonResult(1, ResponseConstants.UpdateTutorName);
                    }
                    else
                    {
                        txscope.Dispose();
                        return JsonResponse.GenerateJsonResult(0, ResponseConstants.SomethingWrong);
                    }
                }
                catch (Exception ex)
                {
                    txscope.Dispose();
                    ErrorLog.AddErrorLog(ex, "EditTutorName");
                    return JsonResponse.GenerateJsonResult(0, ResponseConstants.SomethingWrong);
                }

            }
        }

        [HttpPost]
        public async Task<IActionResult> EditTutorMoNumber(long id, string Monumber)
        {
            using (var txscope = new TransactionScope(TransactionScopeAsyncFlowOption.Enabled))
            {
                try
                {
                    if (!string.IsNullOrEmpty(Monumber))
                    {
                        bool mobileNoExist = MobileNoExists(Monumber);
                        if (mobileNoExist == true)
                        {
                            txscope.Dispose();
                            return JsonResponse.GenerateJsonResult(3, ResponseConstants.MobileNoExist);
                        }
                        else
                        {
                            var result = _tutorService.GetSingle(x => x.Id == id);
                            var tutorUserResult = _userService.GetSingle(x => x.Id == result.UserId);
                            tutorUserResult.MobileNumber = Monumber;
                            var updateResult = await _userService.UpdateAsync(tutorUserResult, Accessor, User.GetUserId());
                            if (updateResult != null)
                            {
                                //StaffLog
                                if (User.IsInRole(UserRoles.Staff))
                                    await _staffLog.InsertAsync(new Log { CreatedDate = DateTime.UtcNow, StaffId = User.GetUserId(), Description = ResponseConstants.UpdateTutorMobileNumber }, Accessor, User.GetUserId());
                                txscope.Complete();
                                return JsonResponse.GenerateJsonResult(1, ResponseConstants.UpdateTutorMobileNumber);
                            }
                        }
                    }
                    txscope.Dispose();

Admin/EasyLearnerAdmin/Views/Tutor/Index.cshtml
@{
    ViewData["Title"] = "Index";
    Layout = "~/Views/Shared/_Layout.cshtml";
}
<div>
    <div style="margin-top:10px;margin-bottom:10px;">
        <button type="button" onclick="AddEditTutor(0)" class="btn btn-primary">Create Tutor</button>
        <button type="button" onclick="DeleteTutors()" class="btn btn-danger">Delete Tutor</button>
    </div>
    <div>
        <table id="dtTutor">
            <thead>
                <tr>
                    <th>Id</th>
                    <th>Tutor Name</th>
                    <th>Lesson</th>
                    <th>Phone no</th>
                    <th>Status</th>
                </tr>
            </thead>
            <tbody></tbody>
        </table>
    </div>
</div>
@section Scripts{
    <script>
        var tableId = "";
        var TutorArray = new Array();

        $(document).ready(function () {
            tableId = "#dtTutor";
            bindTutorTable(tableId);
        });

        function AddEditTutor(id) {
            $("#modalContent").load(`/Tutor/_AddEditTutor/${id}`, function () {
                $("#divModal").modal('show');
            });
        }

        function bindTutorTable(tableId) {
            if ($.fn.DataTable.isDataTable(tableId)) {
                $(tableId).dataTable().fnDestroy();
            }
            dynamic = $(tableId).DataTable({
                "bProcessing": true,
                "bServerSide": true,
                "sAjaxSource": "/Tutor/GetTutorList",
                "initComplete": function (settings, json) { },
                "rowCallback": function (row, data, index) { },
                "order": [[0, ""]],
                "language": {
                    "info": "Showing _START_ to _END_ of _TOTAL_ Tutors",
                    "sInfoEmpty": "Showing 0 to 0 of 0 Tutors"
                },
                "columns": [
                    {
                        "data": "id",
                        "autoWidth": true,
                        "searchable": true,
                        "orderable": true,
                        "render": function (data, type, row) {
                            var element = `<input type="checkbox" class="TutorCheckbox" id="${data}"/>`;
                            return element;
                        }
                    },
                    {
                        "data": "tutorName",
                        "autoWidth": true,
                        "searchable": true,
                        "orderable": true,
                        "render": function (data, type, row) {
                            var content = "";
                            content = content + `<a href="javascript:;" onclick=AddEditTutor(${row.id},false) class="dropdown-item action"><i class="fa fa-trash" aria-hidden="true"></i> Edit Tutor</a>`;
                            //content = content + `<a href="javascript:;" onclick=DeleteStudents(${row.id},true) class=" dropdown-item action"><i class="fa fa-eye" aria-hidden="true"></i> Delete Student</a>`;
                            return dataTableAction(content, data);
                        }
                    },
                    {
                        "data": "lessonName",
                        "autoWidth": true,
                        "searchable": true,
                        "orderable": true,
                        "render": function (data) {

                            if (data != null && data != '') {
                                return data.slice(0, - 1);
                            }
                            else {
                                return data
                            }
                        }
                    
                    },
                       {
                        "data": "mobileNo",
                        "autoWidth": true,
                        "searchable": true,
                        "orderable": true,
                    },
                    {
                        "data": "isActive",
                        "autoWidth": true,
                        "searchable": false,
                        "orderable": false,
                        "className": "admin_toggle",
                         "render": function (data, type, row) {
                            return statusToggle(row.id, data);
                        }
                    }
                ]
            });
             $(tableId).on("change", ".admin_toggle", function (e) {
                const current = $(e.currentTarget).find("input");
                const id = $(current).data("id");

                $.ajax({
                    url: "/Tutor/ManageTutorIsActive",
                    data: { id: id },
                    type: "POST",
                    success: function (response) {
                        Easylearner.HandleResponse(response);
                    },
                    error: function (data) {

                    }
                });
            });
        }

        function DeleteTutors() {
            if (TutorArray.length === 0) {
                alert("Please select atleast one tutor !");
            }


            Easylearner.Confirm("Delete Tutor", Easylearner.typeModel.Warning, "Are you sure?", Easylearner.typeModel.Danger, "Yes, delete it!", function () {
                $.ajax({
                    url: "/Tutor/Removetutors",
                    data: { id: TutorArray },
                    type: "POST",
                    success: function (response) {
                        Easylearner.HandleResponse(response);
                        bindTutorTable(tableId);
                    },
                    error: function (data) {
                        console.log(data);
                    }
                });
            }
            );

        }
        $(document).on("change", ".TutorCheckbox", function () {
            if ($(this).prop("checked") == true) {
                TutorArray.push(parseInt($(this).attr('id')));
            }
            if ($(this).prop("checked") == false) {
                arrayRemove(TutorArray, parseInt($(this).attr('id')));
            }

        })
    </script>

}

Admin/EasyLearnerAdmin/Views/Tutor/ReportOfNumberOfAnswer.cshtml
@model EasyLearner.Service.Dto.TutorFilterLessionWiseAnswerDto
@{
    ViewData["Title"] = "ReportOfNumberOfAnswer";
}

<link href="~/css/bootstrap-datepicker.css" rel="stylesheet" />

<center><h4>Date Of Report OF Number Of Answer By Tutor</h4></center>
<br />
<br />
<form id="frmtutorfilter" method="get">
    <div class="row">
        <input type="hidden" asp-for="Tid" id="Tid" value="@ViewBag.Id" />
        <h5><b>Please specify time interval of the requested Report :-</b></h5>

    </div>
    <br />
    <br />
    <div class="row">
        <div class="col-md-3 form-group">
            <label>From Date <span class="text-danger">*</span></label>

            <input type="text" asp-for="FromDate" id="FromDate" value="" name="FromDate" class="form-control" />
        </div>
        <div class="col-md-3 form-group">
            <label>To Date <span class="text-danger">*</span></label>

            <input type="text" asp-for="ToDate" id="ToDate" value="" name="ToDate" class="form-control" />

        </div>
        <div class="col-md-3 form-group">
            <label></label>
            <input id="btnsubmit" value="Search" class="btn btn-primary " style="    position: relative;    top: 30px;" />
        </div>
    </div>
    
    <br /><br />

</form>

<div id="tutorlistlessionwiseAnswer">
    
    <div>
        <table id="dtTutor">
            <thead>
                <tr>
                    <th>Relevent-Lesson</th>
                    <th>NumberOfAnswer</th>
                </tr>
            </thead>
            <tbody></tbody>
        </table>
    </div>
</div>

@section Scripts{
    <script src="~/js/bootstrap-datepicker.js"></script>
    <script>
       
        $(document).ready(function () {

            $("#tutorlistlessionwiseAnswer").hide();

            $("#btnsubmit").attr("disabled", false);

            $('#FromDate').datepicker({
                changeMonth: true,
                changeYear: true,
                format: "yyyy/mm/dd",
                language: "tr"
            });

            $('#ToDate').datepicker({
                changeMonth: true,
                changeYear: true,
                format: "yyyy/mm/dd",
                language: "tr"
            });

            $("#btnsubmit").click(function () {
                $("#tutorlistlessionwiseAnswer").show();
                tableId = "#dtTutor";
                bindTutorTable(tableId);

            });
            var tableId = "";
            var TutorArray = new Array();


            function bindTutorTable(tableId) {
                if ($.fn.DataTable.isDataTable(tableId)) {
                    $(tableId).dataTable().fnDestroy();
                }
                dynamic = $(tableId).DataTable({
                    "bProcessing": true,
                    "bServerSide": true,
                    bLengthChange: true,
                    "sAjaxSource": "/Tutor/GetCountWiseTutorReport",
                    "initComplete": function (settings, json) { },
                    "rowCallback": function (row, data, index) { },
                    fnServerParams: function (aoData) {
                        aoData.push(
                            { "name": "tid", "value": $("#Tid").val() },
                            { "name": "fromDate", "value": $("#FromDate").val() },
                            { "name": "toDate", "value": $("#ToDate").val() },
                        );
                    },
                    "language": {
                        "info": "Showing _START_ to _END_ of _TOTAL_ Tutors",
                        "sInfoEmpty": "Showing 0 to 0 of 0 Tutors"
                    },
                    "columns": [
                        {
                            "data": "lessonName",
                            "autoWidth": true,
                            "searchable": true,
                            "orderable": true,
                            "render": function (data, type, row) {
                                return data;
                            }
                        }, {
                            "data": "numberOfAnswer",
                            "autoWidth": true,
                            "searchable": true,
                            "orderable": true,
                             "render": function (data, type, row) {
                                return data;
                            }
                        }
                    ]
                });
            }
        });
    </script>
}

Admin/EasyLearnerAdmin/Views/Tutor/TutorAccount.cshtml
@model EasyLearner.Service.Dto.TutorDto
@{
    ViewData["Title"] = "TutorAccount";
}
<h1>TutorAccount</h1>
<form>
    @Html.AntiForgeryToken()
    <input type="hidden" asp-for="Id" name="Id" id="tid" />
    <div class="form-row mt-0">
        <div class="form-group col-md-12">
            <label for="UserName">User name:</label>
            <input type="text" asp-for="UserName" name="UserName" class="form-control" readonly />
        </div>
    </div>

    <div class="form-row mt-0">
        <div class="form-group col-md-12">
            <label for="TutorName">Name of Tutor  <span class="text-danger">*</span></label>
            <input type="text" asp-for="TutorName" name="TutorName" class="form-control" />
            <button type="button" class="btn btn-primary" id="btnEditTutorName" name="btnEditTutorName">Edit</button>
        </div>

    </div>
    <div class="form-row mt-0">
        <div class="form-group col-md-10">
            <label for="MobileNo">Mobile no of Tutor</label>
            <input type="text" class="form-control" aria-label="mobileNo" asp-for="MobileNo" aria-describedby="basic-addon1">
            <button type="button" class="btn btn-primary" id="btnEditTutorMoNumber">Edit</button>
        </div>
    </div>
    <div class="form-row mt-0">
        <div class="form-group col-md-12">
            <a href="#" onclick="EditLesson();">
                Relevant Lesson </a>
        </div>
    </div>
    <div class="form-row mt-0">
        <div class="form-group col-md-5">
            <a href="#" onclick="EditPassword();">Password</a>
        </div>
    </div>
    <div class="form-row mt-0">
        <div class="form-group col-md-5">
            <a href="@Url.Action("Tutorfilter","Tutor")">Back to list</a>
        </div>
    </div>

</form>


@section Scripts{
 <script src="~/js/jquery.mask.js"></script>
@*<script src="~/js/bootstrap-multiselect.js"></script>
<link href="~/css/bootstrap-multiselect.css" rel="stylesheet" />*@

    <script type="text/javascript">

        function EditPassword()
        {
            $("#modalContent").load(`/Tutor/_EditPassword/${@Model.Id}`, function () {
                $("#divModal").modal('show');
            });
        }

        function EditLesson()
        {
            $("#modalContent").load(`/Tutor/_EditLesson/${@Model.Id}`, function () {
                $("#divModal").modal('show');
            });
        }
        $(document).on("click", "#btnEditTutorName", function () {
            $.ajax({
                url: "/Tutor/EditTutorName",
                data: { id: $("#tid").val(), TutorName: $("#TutorName").val() },
                type: "POST",
                success: function (response) {Easylearner.HandleResponse(response); },
                error: function (response) {Easylearner.HandleResponse(response); },
            });
        });

        $(document).on("click", "#btnEditTutorMoNumber", function ()
        {
            $.ajax({
                url: "/Tutor/EditTutorMoNumber",
                data: {
                        id: $("#tid").val(),
                        Monumber: $("#MobileNo").val()
                },
                type: "POST",
                success: function (response) {Easylearner.HandleResponse(response); },
                error: function (response) {Easylearner.HandleResponse(response); },
            });
        });

        $(document).ready(function ()
        {
            $('input[name="MobileNo"]').mask('00000000000');
        });
    </script>
    }

Admin/EasyLearnerAdmin/Views/Tutor/TutorProfile.cshtml
@model EasyLearner.Service.Dto.TutorDto
@{
    ViewData["Title"] = "TutorProfile";
}

<h1>TutorProfile</h1>

<form>
    @Html.AntiForgeryToken()
    <input type="hidden" asp-for="Id" name="Id" id="tid" />
    <div class="form-row mt-0">
        <div class="form-group col-md-12">
            <label for="TutorName">Name of Tutor  <span class="text-danger">*</span></label>
            <input type="text" asp-for="TutorName" name="TutorName" class="form-control" readonly/>
        </div>

    </div>
    <div class="form-row mt-0">
        <div class="form-group col-md-12">
            <label for="UserName">User name:</label>
            <input type="text" asp-for="UserName" name="UserName" class="form-control" readonly />
        </div>
    </div>
    <div class="form-row mt-0">
        <div class="form-group col-md-5">
            <h5><b>Status:-</b></h5>
            @if (Model.IsActive == true)
            {
                <label for="IsActive">ActiveTutor</label>
                <input type="radio" asp-for="IsActive" name="ActiveStatus" value="true" selected><br />
                <label for="IsInActive">InActiveTutor</label>
                <input type="radio" asp-for="IsActive" name="ActiveStatus" value="false"><br />
            }
            else
            {
                <label for="IsActive">ActiveTutor</label>
                <input type="radio" asp-for="IsActive" name="ActiveStatus" value="true"><br />
                <label for="IsInActive">InActiveTutor</label>
                <input type="radio" asp-for="IsActive" name="ActiveStatus" value="false" selected><br />
            }
        </div>
    </div>
    <div class="form-row mt-0">
        <div class="form-group col-md-5">
            <a href="@Url.Action("TutorAccount","Tutor",new { id =Model.Id  })">Tutor Account</a>
        </div>
    </div>
    <div class="form-row mt-0">
        <div class="form-group col-md-5">
            <a href="#">Tutor History</a>
        </div>
    </div>
    <div class="form-row mt-0">
        <div class="form-group col-md-5">
            <a href="@Url.Action("ReportOfNumberOfAnswer","Tutor",new { id =Model.Id  })">Report Of Number Of Answer</a>
        </div>
    </div>
    <div class="form-row mt-0">
        <div class="form-group col-md-5">
            <a href="@Url.Action("Tutorfilter","Tutor")">Back to list</a>
        </div>
    </div>
</form>

@section Scripts
{
    <script>
        $('input[type=radio][name=ActiveStatus]').change(function (e)
        {
            e.preventDefault();
            $.ajax({
                type: "POST",
                url: '@Url.Action("EditTutorStatus","Tutor")',
                data: {
                    id: $("#tid").val(),
                    IsActive:$("input[name='ActiveStatus']:checked"). val(),
                },
                success: function (response) {
                    Easylearner.HandleResponse(response);
                },
                error: function (result) {
                    alert('error');
                }
            });
   
        });
    </script>
}